export default function ExperimentsPage() {
  return (
    <section className="experiments-page">
      <header>
        <p className="eyebrow">Privata</p>
        <h1>Reference experiments</h1>
        <p>
          These experiments are reproducible, offline educational references generated by
          the repository scripts.
        </p>
      </header>
      <div className="experiment-grid">
        <article>
          <h2>Privacy vs. utility</h2>
          <p>Measures query error over a public epsilon grid for supported releases.</p>
        </article>
        <article>
          <h2>Dataset size vs. mean utility</h2>
          <p>Shows how bounded-mean error changes as the fixed public dataset size grows.</p>
        </article>
        <article>
          <h2>Sequential composition</h2>
          <p>Traces repeated requests against a fixed epsilon budget, including rejection.</p>
        </article>
        <article>
          <h2>Neighboring-dataset distributions</h2>
          <p>Compares noisy output distributions for fixed-size datasets differing by one row.</p>
        </article>
      </div>
      <p className="caution">
        Empirical overlap is illustrative, not a formal differential privacy proof. The
        guarantee comes from the documented mechanism and sensitivity proof.
      </p>
    </section>
  );
}
